# Generated by Django 6.0.3 on 2026-03-23 16:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1024)),
                ('score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats_type', models.IntegerField(choices=[(0, 'Travelling'), (1, 'Mining'), (2, 'Farming'), (3, 'Kills')])),
                ('difficulty', models.IntegerField(choices=[(0, 'Peaceful'), (1, 'Easy'), (2, 'Normal'), (3, 'Hard')])),
            ],
            options={
                'unique_together': {('stats_type', 'difficulty')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('total_score', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.leaderboard')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='KillsStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zombie', models.PositiveIntegerField(default=0)),
                ('skeleton', models.PositiveIntegerField(default=0)),
                ('creeper', models.PositiveIntegerField(default=0)),
                ('spider', models.PositiveIntegerField(default=0)),
                ('spider_jockey', models.PositiveIntegerField(default=0)),
                ('zombie_pigman', models.PositiveIntegerField(default=0)),
                ('slime', models.PositiveIntegerField(default=0)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='backend.leaderboardentry')),
            ],
        ),
        migrations.CreateModel(
            name='FarmingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eggs', models.PositiveIntegerField(default=0)),
                ('wheat', models.PositiveIntegerField(default=0)),
                ('mushroom', models.PositiveIntegerField(default=0)),
                ('sugarcane', models.PositiveIntegerField(default=0)),
                ('milk', models.PositiveIntegerField(default=0)),
                ('pumpkin', models.PositiveIntegerField(default=0)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farming', to='backend.leaderboardentry')),
            ],
        ),
        migrations.CreateModel(
            name='MiningStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dirt', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('stone', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('sand', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('cobblestone', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('gravel', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('clay', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('obsidian', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999)])),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mining', to='backend.leaderboardentry')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('friends', models.ManyToManyField(blank=True, to='backend.player')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leaderboardentry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player'),
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.achievement')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.player')),
            ],
            options={
                'unique_together': {('player', 'achievement')},
            },
        ),
        migrations.AddField(
            model_name='player',
            name='achievements',
            field=models.ManyToManyField(blank=True, through='backend.PlayerAchievement', to='backend.achievement'),
        ),
        migrations.CreateModel(
            name='TravellingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walked', models.PositiveBigIntegerField(default=0)),
                ('fallen', models.PositiveBigIntegerField(default=0)),
                ('minecart', models.PositiveBigIntegerField(default=0)),
                ('boat', models.PositiveBigIntegerField(default=0)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travelling', to='backend.leaderboardentry')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardentry',
            unique_together={('player', 'leaderboard')},
        ),
    ]
